### ISSUE TITLE
pywin32 issue under Python 3.6.1 breaks requests-negotiate-sspi as well

### ISSUE THREAD

**Issue by berseus** [brandond/requests-negotiate-sspi#12]
Getting an error due to stricter datetime handling in Python 3.6.1:

```
r = requests.get(url, auth=HttpNegotiateAuth())
Traceback (most recent call last):
  File "C:\bers\winpython\python-3.6.1.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-8021f690f902>", line 4, in <module>
    r = requests.get('http://test-smfbasic:15000/api/InstrumentIds?callerId=bc7611', auth=HttpNegotiateAuth())
  File "C:\bers\winpython\python-3.6.1.amd64\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\bers\winpython\python-3.6.1.amd64\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\bers\winpython\python-3.6.1.amd64\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\bers\winpython\python-3.6.1.amd64\lib\site-packages\requests\sessions.py", line 625, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "C:\bers\winpython\python-3.6.1.amd64\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "C:\bers\winpython\python-3.6.1.amd64\lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 190, in _response_hook
    return self._retry_using_http_Negotiate_auth(r, scheme, kwargs)
  File "C:\bers\winpython\python-3.6.1.amd64\lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 73, in _retry_using_http_Negotiate_auth
    clientauth = sspi.ClientAuth(scheme, targetspn=targetspn, auth_info=self._auth_info)
  File "C:\bers\winpython\python-3.6.1.amd64\lib\site-packages\win32\lib\sspi.py", line 111, in __init__
    None, auth_info)
ValueError: year 30828 is out of range

```
This was apparently solved in requests-kerberos by switching from kerberos-sspi to WinKerberos:
https://github.com/requests/requests-kerberos/issues/99

**Comment by brandond** [comment]
This is a dupe of #7. I'll leave it open though since it appears that WinKerberos has emerged as a reasonable alternative to pywin32.

**Comment by dhirschfeld** [comment]
FWIW pywin32 has been fixed and Release 222 now works on py36!

**Comment by brandond** [comment]
Thanks @dhirschfeld! Procrastination wins again!

**Comment by JonathanHolvey** [comment]
I'm using pywin32 version 222 and Python 3.6.4, but I'm still receiving the out of range error when using `HttpNegotiateAuth()`.

@dhirschfeld what version of Python did you find it works with?

**Comment by dhirschfeld** [comment]
Likely not installed properly. Was it pypiwin32 or maybe installed via pip?

*See:* https://github.com/mhammond/pywin32/issues/748#issuecomment-360328766
